"""
dfo/report.py
=============
NIST SP 800-86 compliant report generator.
Produces Markdown reports covering all four forensic phases.
"""

from __future__ import annotations

from datetime import datetime, timezone

from dfo.models import ForensicFinding


class ReportGenerator:
    """
    Produces Markdown incident reports covering all four
    NIST SP 800-86 phases: Collection, Examination, Analysis, Reporting.
    """

    def generate_markdown(self, case_id: str,
                          findings: list[ForensicFinding],
                          custody, analyst: str = "DFO") -> str:
        now = datetime.now(timezone.utc).isoformat()
        top = [f for f in findings if f.severity_score > 0.3]
        crit = [f for f in findings if f.severity_score >= 0.8]
        engines = sorted({f.engine for f in findings})

        lines = [
            f"# DFIR Report — Case {case_id}",
            "",
            "| Field | Value |",
            "|-------|-------|",
            f"| **Case ID** | {case_id} |",
            f"| **Generated** | {now} |",
            f"| **Analyst** | {analyst} |",
            f"| **Total Findings** | {len(findings)} |",
            f"| **Critical Findings** | {len(crit)} |",
            f"| **Engines Used** | {', '.join(engines)} |",
            "",
            "---",
            "",
            "## 1. Collection Phase (NIST SP 800-86 §4.1)",
            "",
            f"Evidence artifacts were registered with SHA-256 hashing and "
            f"assigned unique identifiers. {len(custody._entries)} "
            f"chain-of-custody entries were recorded.",
            "",
            "## 2. Examination Phase (NIST SP 800-86 §4.2)",
            "",
            f"The following engines were executed: {', '.join(engines)}.",
            f"A total of {len(findings)} raw findings were extracted.",
            "",
            "## 3. Analysis Phase (NIST SP 800-86 §4.3)",
            "",
            f"Findings were scored using a weighted algorithm aligned with "
            f"NIST SP 800-61 Rev. 2 impact categories (IOC=40%, "
            f"Persistence=30%, Exfiltration=30%).",
            "",
            f"{len(top)} findings exceeded the 0.3 severity threshold.",
            "",
            "### Top Findings",
            "",
            "| # | Score | Severity | Category | Engine | Title |",
            "|---|-------|----------|----------|--------|-------|",
        ]

        for i, f in enumerate(top[:30], 1):
            lines.append(
                f"| {i} | {f.severity_score:.3f} | "
                f"{f.severity.value} | {f.category.value} | "
                f"{f.engine} | {f.title} |"
            )

        lines += [
            "",
            "## 4. Reporting Phase (NIST SP 800-86 §4.4)",
            "",
            "This report was auto-generated by the Digital Forensics "
            "Orchestrator (DFO). The chain-of-custody log is stored "
            f"at `cases/{case_id}/coc_{case_id}.jsonl`.",
            "",
            "---",
            f"*Report generated by DFO v1.0.0 on {now}*",
        ]
        return "\n".join(lines)
